# Generated by Django 4.1.2 on 2022-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
