# Generated by Django 4.1.2 on 2022-11-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='Emp_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='emp_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
    ]
