# Generated by Django 4.1.2 on 2022-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_fname_student_emp_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.PositiveIntegerField()),
                ('Emp_name', models.CharField(max_length=180)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emp_id',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Emp_name',
            new_name='fname',
        ),
    ]
